const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),script=fs.readFileSync(path.join(__dirname,'app.js'),'utf8');
async function boot(initial={}){
 const elements={},data=new Map(Object.entries(initial));
 for(const m of html.matchAll(/<\w+[^>]*id="([^"]+)"[^>]*>/g))elements[m[1]]={value:(m[0].match(/value="([^"]*)"/)||[])[1]||'',checked:/\schecked/.test(m[0]),type:(m[0].match(/type="([^"]*)"/)||[])[1]||'',style:{},classList:{add(){},remove(){}}};elements.beds.value='3';
 let feed=JSON.parse(fs.readFileSync(path.join(__dirname,'properties.json'),'utf8'));let fail=false;
 const context={URL,Date,setTimeout,document:{getElementById:id=>elements[id]||(elements[id]={value:'',style:{}}),querySelectorAll:()=>[],querySelector:()=>({classList:{add(){}}})},localStorage:{getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)},location:{protocol:'http:'},navigator:{},window:{},fetch:async()=>{if(fail)throw Error('offline');return {ok:true,json:async()=>feed}}};vm.createContext(context);vm.runInContext(script,context);await context.loadListings();
 return {run:s=>vm.runInContext(s,context),context,e:elements,data,setFeed:f=>feed=f,getFeed:()=>feed,setFail:v=>fail=v};
}
test('live search, shortlist, saved search and safe note rendering',async()=>{const t=await boot();t.run('resetSearch()');assert.equal(t.e.count.textContent,`${t.getFeed().properties.length} matching properties`);t.run('toggleShort(88467);currentTab="shortlist";runSearch()');assert.equal(t.e.count.textContent,'1 matching property');t.e.maxPrice.value='800000';t.run('saveSearch()');t.e.maxPrice.value='1';t.run('loadSaved()');assert.equal(t.e.maxPrice.value,'800000');t.data.set('note_88467','</textarea><script>bad()</script>');t.run('showDetail(88467)');assert.equal(t.e.note_88467.value,t.data.get('note_88467'));assert.ok(!t.e.detail.innerHTML.includes('bad()'))});
test('withdrawn listing remains accessible in shortlist and notes survive refresh failure',async()=>{const t=await boot();t.run('toggleShort(88467)');t.data.set('note_88467','Keep');t.setFeed({...t.getFeed(),properties:t.getFeed().properties.filter(p=>p.id!==88467)});await t.context.loadListings();t.run('currentTab="shortlist";runSearch()');assert.match(t.e.results.innerHTML,/No longer in latest feed/);t.run('showDetail(88467)');assert.equal(t.e.note_88467.value,'Keep');t.setFail(true);assert.equal(await t.context.loadListings(),false);assert.match(t.e.dataStatus.textContent,/Keeping previously loaded/)});
test('legacy Cooper Brouard bookmarks migrate once and removed bookmarks stay removed',async()=>{const t=await boot({gp_shortlist:'[1]',note_1:'Legacy note'});assert.ok(JSON.parse(t.data.get('gp_shortlist')).includes(88467));assert.equal(t.data.get('note_88467'),'Legacy note');t.run('toggleShort(88467)');await t.context.loadListings();assert.ok(!JSON.parse(t.data.get('gp_shortlist')).includes(88467));assert.equal(t.data.get('note_1'),'Legacy note')});
test('corrupt stored JSON does not break startup; source strings are escaped',async()=>{const t=await boot({gp_shortlist:'bad',gp_saved:'bad',gp_property_snapshots:'[]'});assert.ok(t.e.count.textContent);const card=t.run('card({...properties[0],name:"<img src=x onerror=bad()>"})');assert.ok(card.includes('&lt;img'));assert.ok(!card.includes('alt="<img'))});
