const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
const {parseProperty,parseIndex,robotsAllows,collect}=require('./collector.cjs');
const card={url:'https://www.cooperbrouard.com/property/123/',market:'Local Market',location:'St Martin\'s GY4 6LR'};
function html({status='for-sale',department='residential-sales',description='A &amp; B',price=895000,bedrooms=3,label='£895,000',type='bungalow'}={}){return `<body class="availability-${status} department-${department} on-market-yes property_type-${type}"><meta property="og:description" content="${description}"><div class="cb-single-property-header__top"><h2>${label}</h2></div><script type="application/ld+json">${JSON.stringify({'@graph':[{'@type':['Residence','SingleFamilyResidence'],name:'A &amp; B',numberOfBedrooms:bedrooms,image:['https://cdn.cooperbrouard.com/media/photo.jpg','javascript:bad'],address:{streetAddress:'Road'}},{offers:{price,businessFunction:'https://purl.org/goodrelations/v1#Sell'},datePosted:'2026-09-01'}]})}</script>`}
test('extracts explicit facts and safe photo URLs without inventing garden facts',()=>{const p=parseProperty(html(),card,'now');assert.equal(p.price,895000);assert.equal(p.beds,3);assert.equal(p.type,'Bungalow');assert.equal(p.description,'A & B');assert.equal(p.parking,null);assert.equal(p.garden,null);assert.equal(p.photos.length,1)});
test('preserves missing description/type/bedrooms and POA',()=>{const p=parseProperty(html({description:'',type:'',bedrooms:null,price:0,label:'POA'}),card,'now');assert.equal(p.price,null);assert.equal(p.type,null);assert.equal(p.beds,null);assert.equal(p.description,'')});
test('excludes sold, rental, and land; retains under-offer status',()=>{assert.equal(parseProperty(html({status:'sold'}),card,'now'),null);assert.equal(parseProperty(html({department:'residential-lettings'}),card,'now'),null);assert.equal(parseProperty(html({type:'land'}),card,'now'),null);assert.equal(parseProperty(html({status:'under-offer'}),card,'now').status,'under')});
test('maps St Pierre du Bois to existing parish filter',()=>assert.equal(parseProperty(html(),{...card,location:'St Pierre du Bois GY7 9AA'},'now').parish,"St Peter's"));
test('index coverage changes fail closed',()=>assert.throws(()=>parseIndex('Showing 1–1 of 2 properties<div class="cb-card-property"><a href="https://www.cooperbrouard.com/property/123/">','Local Market'),/coverage mismatch/));
test('robots uses specific rules, wildcard paths and longest allow',()=>{assert.equal(robotsAllows('User-agent: *\nDisallow:', '/property/1/'),true);assert.equal(robotsAllows('User-agent: *\nDisallow: /property/', '/property/1/'),false);assert.equal(robotsAllows('User-agent: *\nDisallow: /property/\nAllow: /property/1/', '/property/1/'),true);assert.equal(robotsAllows('User-agent: GuernseyPropertyFinder\nDisallow: /\nUser-agent: *\nAllow: /', '/property/1/'),false)});
test('network failure preserves previous published feed',async()=>{const file=path.join(__dirname,'properties.json');const before=await fs.readFile(file);const original=global.fetch;global.fetch=async()=>{throw Error('Simulated source outage')};try{await assert.rejects(collect(),/Simulated source outage/)}finally{global.fetch=original}assert.deepEqual(await fs.readFile(file),before)});

test('uses dwelling type when investment and garage tags precede it',()=>{assert.equal(parseProperty(html({type:'garage property_type-house'}),card,'now').type,'House');assert.equal(parseProperty(html({type:'buy-to-let-investment property_type-flat-apartment'}),card,'now').type,'Apartment')});
